CREATE TABLE [dbo].[Quote] (
    [Id]        INT      PRIMARY KEY     IDENTITY (1, 1) NOT NULL,
	[Guid] UNIQUEIDENTIFIER NOT NULL UNIQUE, 
    [Content]   VARCHAR (250) NOT NULL UNIQUE,
    [Quotee]    VARCHAR (50)  NOT NULL,
    [DateAdded] DATETIME DEFAULT GETUTCDATE() NOT NULL  
    
);

